name: "❓ Support Question"
description: "Ask a general support question"
title: '❓ <title>'
labels: [
  'support question'
]
body:
- type: markdown
  attributes:
    value: We reserve the right to change how we offer support.
- type: markdown
  attributes:
    value:  For now, please review the resources below, and *then* if you still have a question, go ahead and ask.
- type: markdown
  attributes:
    value: ---
- type: markdown
  attributes:
    value: "## Other Support Resources "
- type: markdown
  attributes:
    value: |
      - Slack Community Chat: https://babeljs.slack.com (you can sign-up at https://slack.babeljs.io/ for an invite)
      - StackOverflow: https://stackoverflow.com/questions/tagged/triembed-quercus using the tag `triembed-quercus`
      - Twitter: If it's just a quick question you can ping our Twitter: https://twitter.com/babeljs
      - Also have a look at the readme for more information on how to get support:
        https://github.com/triembed/quercus/blob/master/README.md
- type: checkboxes
  attributes:
    label: Have you checked other resources for this?
    options:
    - label: I have searched the suggested resources
      required: true
- type: textarea
  attributes:
    label: Your Question
    description: Your general support question
  validations:
    required: true
