#!/bin/bash -x
# Add -x to above line for more verbose output
# Clean out the files installed by installit
# WARNING: This will remove $targetdir/{esp-idf, aarvark, the-ant}
# By default leaves packages installed. See usage().
# B E W A R E using -completely. Look long and hard at the 
# package list and ask yourself if you will cripple your
# system with this (the answer is yes). This feature is a 
# convenience for Docker development.
# Currently ignored unless you're root.

# see installit for more relevant notes

# Bump this per push

version="0.02"

# Append your email addr here and append your name to the 
# copyright list with commas. 

# pete@soper.us

# MIT License
#
# Copyright 2022 Peter James Soper
#
# Permission is hereby granted, free of charge, to any person 
# obtaining a copy of this software and associated 
# documentation files (the "Software"), to deal in the
# Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, 
# distribute, sublicense, and/or sell copies of the
# Software, and to permit persons to whom the Software is 
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall
# be included in all copies or substantial portions of the 
# Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY 
# KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE 
# WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
# PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS
# OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
# OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

# Have to manually keep this default sync'd with installit

targetdir=~

# Don't modify lines below this one

# Ditto for this list

packages="git wget flex bison gperf python3 python3-venv cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0 direnv curl"

true=1
false=0


completely=$false

usage() {
  echo $1
  echo "usage: cleanit [-target] [-completely]"
  exit 1
}

while [ $# -gt 0 ] ; do
  if [ $1 = "-completely" ] ; then
    completely=$true
    shift
  elif [ $1 = "-version" ] ; then
    echo "version: $version"
    exit 0
  else
    usage "unknown option: $1"
  fi
fi

if [ ! $USER = "root" ] ; then
  SUDO=sudo
fi

if [ $completely -eq $true ] ; then
  if [ ! $USER = "root" ] ; then
    echo "-completely currently ignored unless root"
  else
    for package in $packages ; do
      $SUDO apt-get remove -y $package >/tmp/log.$$ 2>&1
    done
    rm -rf $targetdir/.nvm
  fi
fi

rm -rf $targetdir/esp-idf
rm -rf $targetdir/aardvark
rm -rf $targetdir/the-ant

