#!/bin/bash
# Add -x to above line for more verbose output
#
# TriEmbed ESP32/Dialog FPGA Project
#
# Tool chain installation script
# The expectation is that much of this will be put under
# ../common and sourced by the remainder of this script that
# specializes it with arguments to the common script but 
# discussion is needed as the WSL version takes shape and the
# Windows version is thought through (by Windows developers).

# Bugs:
#  0) The the-ant repo needs an edit of main/i2c.h to prefix
#     the two uint8_t decls with "extern". This can be done
#     starting when the first "npm build" is listed as long
#     as the edits are done before "idf build in the-ant" is
#     displayed. 
#  1) The nvm install is not properly editing .bashrc such
#     that nvm cannot be found outside of the installit
#     script. This used to work!
#
# Todo:
#  1) Should be able to detect and elide redundant package
#     installs and perhaps npm install and npm run build

# Bump this per push

version="0.15"

# Add your email here and append your name to the copyright list with commas

# pete@soper.us

# MIT License
#
# Copyright 2022 Peter James Soper
#
# Permission is hereby granted, free of charge, to any person 
# obtaining a copy of this software and associated 
# documentation files (the "Software"), to deal in the
# Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, 
# distribute, sublicense, and/or sell copies of the
# Software, and to permit persons to whom the Software is 
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall
# be included in all copies or substantial portions of the 
# Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY 
# KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE 
# WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
# PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS
# OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
# OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

# The pathname to the Espressif esp-idf tools. 
# NOTE WELL that the aardvrk, the-ant, and triembedtools repos
# will be placed along side esp-idf, not within esp-idf
# The default is installation in the user's home directory
# Todo rename thetools to triembedtools?
# NEED A NAME FOR THE WHOLE PROJECT!!!

targetdir=~

# The git branch label for the exact version of tools to
# install. If this variable does not match the branch of an
# existing esp-idf the script must be aborted because there
# is the likelihood that the submodules are not right.
# The v4.4 branch is the latest Espressif stable branch.
# the v5.0 branch is the bleeding edge branch that is used
# by the Arduino runtime. NOTE that the TriEmbed project is
# currently committed to the stable branch. Also note that
# the v5.0 branch is updated frequently, so it is not safe to
# assume it is stable and frequent git pull operations and
# submodule operations are needed: neither of which are done
# by this script.

targetbranch="v4.4"

# This is a todo. Just use raw list for Ubuntu until later
# Uncomment ONE of these three variable assignments below enable the prerequsite package installation for your system
# Todo automate the OS detection
# Todo May have to use while for per package to avoid spewage
# Todo if idf version 5.0 install Python 3.10

# Ubuntu and Debian:

# The nvm version
nodeversion="14"

#getpackages="sudo apt-get install git wget flex bison gperf python3 python3-venv cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0 direnv curl"

# CentOS 7 & 8:

#CentOS 7 is still supported but CentOS version 8 is recommended for a better user experience.

#getpackages="sudo yum -y update && sudo yum install git wget flex bison gperf python3 cmake ninja-build ccache dfu-util libusbx direnv curl"

packages="git wget flex bison gperf python3 python3-venv cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0 direnv curl"

#Arch:

#getpackages="sudo pacman -S --needed gcc git make flex bison gperf python cmake ninja ccache dfu-util libusb direnv"

#NOTE:  CMake version 3.16 or newer is required for use with ESP-IDF. Run “tools/idf_tools.py install cmake” to install a suitable version if your OS version doesn’t have one.
#todo automate this

#### Do not change lines below here

# No need for sudo if root
if [ $USER = "root" ] ; then
  SUDO=""
else
  SUDO="sudo"
fi

# Detail proper usage of the script command and error exit

usage() {
  echo $1
  echo "usage: installit [ -targetdir <path> ] [ -branch <branch id> ]"
  exit 1
}

# Get a Y or y or N or n after a prompt. Return true if Y or
# y, false if N or n. Cannot escape until an acceptable 
# answer is input. Use ctrl-C to break out.
# Todo signal handler to ensure exit 1 with ctrl-C if we
# don't get this for free

getyes() {
  while [ 1 -eq 1 ] ; do
    echo "$1"
    read ans
    if [ $ans = "Y" ] || [ $ans = "y" ] ; then
      return 0
    elif [ $ans = "N" ] || [ $ans = "n" ] ; then
      return 1
    else
      echo "Answer MUST be Y, y, N, or n"
    fi
  done
}

# Output a fatal error message and error exit

fatal() {
  echo $1
  rm -f /tmp/log.$$
  exit 1
}

# Brute force handling of option switches

while [ $# -ge 2 ] ; do
  switch=$1
  shift
  case $switch in
    -targetbranch) targetbranch=$1;
             $shift;
	     break;;
    -targetdir) targetdir=$1;
 	     shift;
	     break;;
    -version) echo "version: $version";
	     exit 0;;
    *): usage "unknown option switch: $1";
	     exit 1;;
  esac
done

if [ $# -gt 0 ] ; then
  if $1 = "-version" ] ; then
    echo "version: $version"
    exit 0
  else
    usage "orphan command line option: $@"
  fi
fi

# Install the required packages
# Todo need to just point a finger at the packages that did
# not install properly

#if "$getpackages " -eq " " ] ; then
#  fatal "must uncomment one package install line"
#fi

#$getpackages >/tmp/log.$$ 2>&1
#if [ $? -ne 0 ] ; then
#  Grep this to flag package names?
#  cat /tmp/log.$$
#  fatal "packages did not all install properly"
#else
#  echo "packages installed
#fi

echo "installing packages"

for package in $packages ; do
  $SUDO apt-get install -y $package >/tmp/log.$$ 2>&1
  if [ $? -ne 0 ] ; then
    cat /tmp/log.$$
    fatal "Could not install $package"
  fi
done

echo "Prerequisite packages installed"

# Is the directory present and not empty?

if [ -d $targetdir/esp-idf ] ; then
  present=1
else
  present=0
fi
# If dir is present then qualify it. If user wants to bail
# then error exit

if [ $present -eq 1 ] ; then
  cd $targetdir/esp-idf
  git branch | grep $targetbranch >/dev/null
  if [ $? -eq 0 ] && [ -e $targetdir/esp-idf/.cloned ] && [ -e $targetdir/esp-idf/.submodules ] ; then
    getyes "$targetdir/esp-idf is present and usable. Skip erasing and doing a new clone? use current repo? (Y/N)"
    if [ $? -eq 0 ] ; then
      present=1
    else
      rm -rf $targetdir/esp-idf
      if [ $? -ne 0 ] ; then
	fatal "Could not erase $targetdir/esp-idf"
      else
	present=0
      fi
    fi
  else
    getyes "$targetdir/esp-idf is on the wrong branch: delete and recreate it? (y/n)"
    if [ $? -eq 0 ] ; then
      rm -rf $targetdir/esp-idf
      if [ $? -ne 0 ] ; then
	fatal "Could not erase $targetdir/esp-idf"
      else
	present=0
      fi
    fi
  fi  
fi

if [ $present -eq 0 ] ;then
  cd $targetdir
  git clone http://github.com/espressif/esp-idf.git >/tmp/log.$$ 2>&1
  if [ $? -ne 0 ] ; then
    cat /tmp/log.$$
    fatal "Could not clone espressif esp-idf repository"
  else
    cd esp-idf
    touch .cloned
    git branch $targetbranch
    echo "loading submodules: this takes longer than the repo clone, be patient"
    git submodule update --init --recursive >/tmp/log.$$ 2>&1
    if [ $? -ne 0 ] ; then
      cat /tmp/log.$$
      fatal "git submodule update --init --recursive failed"
    else
      touch .submodules
    fi
    ./install.sh >/tmp/log.$$
    if [ $? -ne 0 ] ; then
      cat /tmp/log.$$
      fatal "esp-idf/intall.sh failed"
    fi
  fi
fi

echo "valid esp-idf repo"

for repo in aardvark the-ant ; do
  cd $targetdir
  if [ -d $targetdir/$repo ] ; then
    echo "pull on $repo"
    cd $targetdir/$repo
    git pull >/tmp/log.$$
    if [ $? -ne 0 ] ; then
      cat /tmp/log.$$
      fatal "could not update existing $repo repo"
    fi
  else
    echo "clone of $repo"
    git clone http://github.com/triembed/$repo.git >/tmp/log.$$ 2>&1
    if [ $? -ne 0 ] ; then
      cat log.$$
      fatal "could not clone $repo"
    fi
  fi
done

echo "aardvark and the-ant repos are present and up to date"

echo "setting up direnv"

if [ ! -f $targetdir/the-ant/.direnv ] ; then
  echo ". $targetdir/esp-idf/export.sh >/dev/null 2>&1" >$targetdir/the-ant/.direnv
  echo "echo IDF initialized" >>$targetdir/the-ant/.direnv
  echo "nvm use $nodeversion" >>$targetdir/the-ant/.direnv
  cd $targetdir/the-ant
fi

grep "direnv hook bash" ~/.bashrc
if [ $? -ne 0 ] ; then
  echo 'eval "$(direnv hook bash)"' >>~/.bashrc
  if [ $? -ne 0 ] ; then
    fail "could not edit ~/.bashrc"
  fi
fi

# Something is causing this file to be created with a 
# bogus source command. Mysterious!
cp $targetdir/the-ant/.direnv $targetdir/the-ant/.envrc
rm $targetdir/the-ant/.direnv
cd $targetdir/the-ant
direnv allow

if [ ! -d $HOME/.nvm ] ; then
  echo "installing nvm"
  curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash >/tmp/log.$$ 2>&1
  if [ $? -ne 0 ] ; then
    cat /tmp/log.$$
    fatal "nvm could not be installed"
  fi
fi

. ~/.bashrc >/dev/null 2>&1

export NVM_DIR=$HOME/.nvm
source $NVM_DIR/nvm.sh >/dev/null 2>&1
echo "install node version $nodeversion"
nvm install $nodeversion >/tmp/log.$$ 2>&1
if [ $? -ne 0 ] ; then
  cat /tmp/log.$$
  fatal "could not install nvm version $nodeversion"
fi

cd $targetdir/aardvark
echo "installing npm in aardvark"
npm install >/tmp/log.$$ 2>&1
if [ $? -ne 0 ] ; then
  cat /tmp/log.$$
  fatal "could not intall npm in aardvark"
fi

echo "building npm in aardvark"
npm run build >/tmp/log.$$ 2>&1
if [ $? -ne 0 ] ; then
  cat /tmp/log.$$
  fatal "could not npm run build in aardvark"
fi
  
cd $targetdir/the-ant/ant
echo "installing npm in the-ant"
npm install >/tmp/log.$$ 2>&1
if [ $? -ne 0 ] ; then
  cat /tmp/log.$$
  fatal "could not intall npm in the-ant/ant"
fi
  
echo "building npm in the-ant"
npm run build >/tmp/log.$$ 2>&1
if [ $? -ne 0 ] ; then
  cat /tmp/log.$$
  fatal "could not npm run build in the-ant"
fi

echo "idf build in the-ant"
cd $targetdir/the-ant
rm -rf build
rm -rf ant/dist/js/*.map
. $targetdir/esp-idf/export.sh >/dev/null 2>&1

idf.py build >/tmp/log.$$ 2>&1
if [ $? -ne 0 ] ; then
  cat /tmp/log.$$
  fatal "could not do IDF build in the-ant"
fi

echo "installation complete"
echo "Now ready to enter aardvark and use npm run serve"
echo "Then enter the-ant and use idf.py flash

rm -f log.$$

exit 0
